// Export all action creators from slices
export {
  setLoading as setAuthLoading,
  setError as setAuthError,
  clearError as clearAuthError,
  loginSuccess,
  loginFailure,
  registerSuccess,
  registerFailure,
  logout,
  updateUserProfile,
  setUserFromToken,
  initializeAuth,
} from './authSlice'

export {
  toggleSidebar,
  setSidebarOpen,
  toggleMobileNav,
  setMobileNavOpen,
  openModal,
  closeModal,
  closeAllModals,
  addToast,
  removeToast,
  clearToasts,
  setLoading,
  setGlobalLoading,
  setTheme,
  toggleTheme,
  setSearchQuery,
  setSearchFilters,
  clearSearch,
  setPagination,
  nextPage,
  prevPage,
  resetPagination,
  setViewMode,
  toggleViewMode,
  setError,
  clearError,
  clearAllErrors,
  resetUI,
} from './uiSlice'
